.PHONY: all clean
all: decision_function failure_manager input_manager P1 P2 P3 watchdog

decision_function:	decision_function.c makefile
	gcc -g -Wall -Werror -Wextra decision_function.c -o decision_function -lpthread

failure_manager:	failure_manager.c makefile
	gcc -g -Wall -Werror -Wextra failure_manager.c -o failure_manager -lpthread

input_manager:	input_manager.c makefile
	gcc -g -Wall -Werror -Wextra input_manager.c -o input_manager -lpthread

P1:	P1.c makefile
	gcc -g -Wall -Werror -Wextra P1.c -o P1 -lpthread

P2:	P2.c makefile
	gcc -g -Wall -Werror -Wextra P2.c -o P2 -lpthread

P3:	P3.c makefile
	gcc -g -Wall -Werror -Wextra P3.c -o P3 -lpthread

watchdog:	watchdog.c makefile
	gcc -g -Wall -Werror -Wextra watchdog.c -o watchdog -lpthread

#run: $(shell ./input_manager FAILURE dataset.csv)

clean:
	/bin/rm -f *~ decision_function
	/bin/rm -f *~ failure_manager
	/bin/rm -f *~ P1
	/bin/rm -f *~ P2
	/bin/rm -f *~ P3
	/bin/rm -f *~ watchdog
	/bin/rm -f *~ input_manager